FROM bde2020/spark-master:3.0.1-hadoop3.2

USER root

RUN apk add --no-cache python3 py3-pip build-base python3-dev

RUN pip3 install --no-cache-dir numpy pandas

ENV PYSPARK_PYTHON=python3

USER spark
