echo "Deleting /test..."
docker exec -it namenode bash -c "hdfs dfs -rm -r -f /test"
echo "Creating /test..."
docker exec -it namenode bash -c "hdfs dfs -mkdir /test"
echo "Putting /test..."
docker exec -it namenode bash -c "hdfs dfs -put ./testing/test1/hello.txt /test"
echo "Printing /test/hello.txt"
docker exec -it namenode bash -c "hdfs dfs -cat /test/hello.txt"
echo "Finished..."